name: First practice workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Run the lint
        run: npm run lint
      - name: Run test
        run: npm test
